# Homebrew Nginx on this Mac.
worker_processes auto;
error_log /usr/local/var/log/nginx/user-error.log;
pid /usr/local/var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /usr/local/etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /usr/local/var/log/nginx/user-access.log;
    sendfile on;
    keepalive_timeout 65;
    server_tokens off;

    include /usr/local/etc/nginx/servers/*.conf;
}
